name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
   enviroment:
     DOCKERHUB_USRE: ${{ vars.DOCKERHUB_USER }}
   deploy:
     runs-on: self-hosted
     steps:
       - name: checkout code
         uses: actions/checkout@v4

       - name: deploy with docker compose
         run: docker compose up -d --build
   
